### ISSUE TITLE
got as dependency

### ISSUE THREAD

**Issue by floatdrop** [vdemedes/got-retry#1]
> Does not have a got dependency set, install it yourself

Why so? `got` is pretty minimal package and `got-retry` depends on its API (so at least it should be bound to `^4` version).

**Comment by vdemedes** [comment]
Thought that maybe developers might want to install specific version of `got`.

**Comment by vdemedes** [comment]
I think you are right, I should include it to avoid any confusion.

**Comment by vdemedes** [comment]
Updated `got-retry` with included `got` is released under `got-retry@1.0.4` on npm.

**Comment by floatdrop** [comment]
Cool! :+1:
