### ISSUE TITLE
Pluggable retry strategies

### ISSUE THREAD

**Issue by h2non** [vdemedes/got-retry#3]
It would be great adding support to plug in additional failure detection strategies, like using this [package](https://github.com/h2non/is-fail).

**Comment by vdemedes** [comment]
I think there's no need for that, because `retry` works quite good for `got-retry` use-case. The only task this module has is to retry requests on **network failure** and it does it well ;)

**Comment by h2non** [comment]
I see your point, but disagree. Retry scenarios can be usually triggered by other reasons than just network communication errors handled by node.

**Comment by vdemedes** [comment]
The thing is, `got-retry` tries to handle one task exactly - retry any request, when a random network failure comes in the way. It is not error handling, it is just "error-repeat-error-repeat" kind of thing.

So I would recommend using `retry` module, if you need to do some custom error handling and retry requests.

**Comment by h2non** [comment]
Thanks for the tip, Indeed, I'm already using it with additional support for third party plugins.

Tiny modules with one responsability should not strictly mean closed to extensibility, especially when it tries to cover requirements which usually tends to be ad-hoc to the user needs.

**Comment by vdemedes** [comment]
Agree on that statement, but as developers really love to say: "it depends" :D
