### ISSUE TITLE
Retry got.stream

### ISSUE THREAD

**Issue by techniq** [vdemedes/got-retry#4]
It looks like `got-retry` [doesn't support](https://github.com/vdemedes/got-retry/blob/master/index.js#L144-L145) retrying when using streams.  Any chance of getting this added as I'm using got.stream and need to retry on 5xx errors.  I've been trying to create my own wrapper with [multistream](https://github.com/feross/multistream) `.on('error', ...)` but have been having difficultly getting it right.

**Comment by techniq** [comment]
I ended up coming up with this using highland.js (might be overkill but works)

```js
function retryStream(streamFunc, retries) {
  let stream = _((push, next) => {
    let attempt = 1;
    retries = retries || 3;

    (function loop() {
      // console.log('loop ' + attempt);

      if (attempt <= retries) {
        let streamPage = streamFunc()
          .on('error', (err) => {
            // console.log('error, retrying');
            attempt++;
            loop();
          })
          .on('response', () => {
            // console.log('success');
            streamPage.pipe(stream);
          })
      } else {
        push('Max attempts reached');
      }
    }());
  });

  return stream;
}
```

example usage (contrived example)
```js
  streamPageRetry(page, perPage, retries) {
    return retryStream(() => got.stream('http://localhost'), retries)
      .pipe(JSONStream.parse('data.*'))
  }
```

**Comment by vdemedes** [comment]
@techniq I should've clarified this in the Readme, but this module's functionality was included in the `got` module itself - https://github.com/sindresorhus/got#retries. I recommend you to use `got` module directly ;)

**Comment by techniq** [comment]
@vdemedes Thanks, although the retry support in got doesn't include 5xx errors (just connectivity errors).  Found a solution to my problem [here](https://github.com/sindresorhus/got/issues/119#issuecomment-156662937) though.  Thanks.

**Comment by vdemedes** [comment]
@techniq 5xx errors are not meant to be auto-handled, because 5xx error is a server response. Retry functionality should handle only network issues, where it's safe to retry a request and don't expect a double-action in your application. Let me know if anything is unclear, so that I can further clarify ;)

**Comment by techniq** [comment]
Understood, thanks
